Pupil Invisible LSL Relay
labstreaminglayer/App-PupilLabs pull request #9
Opened 2019-11-08 15:10 UTC by romanroibu

2019-11-08 15:24 UTC, cboulay commented on pupil_invisible_lsl_relay/README.md
> +git clone https://github.com/romanroibu/App-PupilLabs.git
This should be updated for the pull request.

2019-11-08 15:27 UTC, cboulay commented
Hi @romanroibu , can you give a brief description of what's changing? There have been users in the past who were a bit sidelined by the previous major change to the pupil LSL plugin dataformat; it would be good if we could provide an explanation. What's the Pupil Invisible Gaze Relay device monitor? What are the advantageous for this vs. the pupil_capture method? etc.

Thank you!

2019-11-08 15:36 UTC, papr commented
This is an additional lsl app. The old one does not change. Only thing that should change is the instructions

2019-11-09 12:29 UTC, papr requested changes
@romanroibu Please add a top-level readme explaining the main difference between the two lsl relays and their intended usages (Pupil Core + Capture, Pupil Invisible + stand-alone). Also point to the respective readme files in the subfolders for more information.

2019-11-09 12:38 UTC, papr commented on setup.py
> +from setuptools import setup, find_packages
`find_packages` is unused

2019-11-10 18:50 UTC, gmierz commented
I'm not a reviewer here, but I want to make a friendly request to add a relay version control number to this similar to what was done here: https://github.com/labstreaminglayer/App-PupilLabs/pull/7

Please, and thank you! :)

2019-11-11 09:39 UTC, papr requested changes
I think it would be better to link to the product pages instead.

2019-11-11 09:39 UTC, papr commented on README.md
> +- **`pupil_capture`** contains a [Pupil Capture][pupil-capture-app] plugin that works with the [Pupil Core headset][pupil-core-headset].
```suggestion
- **`pupil_capture`** contains a [Pupil Capture][pupil-capture-app] plugin that works with the [Pupil Core headset][pupil-core-headset] and the [VR/AR add-ons][vr-ar-addons].
```

2019-11-11 09:39 UTC, papr commented on README.md
> +[pupil-invisible-lsl-readme]: https://github.com/labstreaminglayer/App-PupilLabs/blob/master/pupil_invisible_lsl_relay/README.md
```suggestion
[pupil-invisible-lsl-readme]: https://github.com/labstreaminglayer/App-PupilLabs/blob/master/pupil_invisible_lsl_relay/README.md
[vr-ar-addons]: https://pupil-labs.com/products/vr-ar/
```

2019-11-11 09:39 UTC, papr commented on README.md
> +[pupil-capture-app]: https://docs.pupil-labs.com/core
```suggestion
[pupil-capture-app]: https://github.com/pupil-labs/pupil/releases/latest
```

2019-11-11 09:39 UTC, papr commented on README.md
> +[pupil-core-headset]: https://docs.pupil-labs.com/core/hardware
```suggestion
[pupil-core-headset]: https://pupil-labs.com/products/core
```

2019-11-11 09:39 UTC, papr commented on README.md
> +[pupil-invisible-headset-and-app]: https://docs.pupil-labs.com/invisible
```suggestion
[pupil-invisible-headset-and-app]: https://pupil-labs.com/products/invisible/
```

2019-11-11 09:39 UTC, papr commented on README.md
> +- **`pupil_invisible_lsl_relay`** is a command line tool for publishing data from the [Pupil Invisible headset][pupil-invisible-headset-and-app].
```suggestion
- **`pupil_invisible_lsl_relay`** is a command line tool for publishing data from [Pupil Invisible][pupil-invisible-headset-and-app].  
```

2019-11-11 09:51 UTC, papr approved these changes

2019-11-11 10:12 UTC, papr commented
@cboulay please also have a look at the release notes draft

2019-11-12 21:03 UTC, merged